#!/usr/bin/python -tt
# Copyright (C) 2012 by The Linux Foundation and contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
import re

if len(sys.argv) != 2:
    print 'Usage: %s syslog-line' % (sys.argv[0])
    sys.exit(1)

logline = sys.argv[1]

CONFIG  ='/etc/howler/howler.ini'
REGEXES ='/etc/howler/syslog-regexes'

fh = open(REGEXES, 'r')
while True:
    regline = fh.readline()
    if not regline:
        sys.exit(0)

    if regline[0] == '#':
        continue

    regline = regline.strip()

    res = re.search(regline, logline)

    if res:
        from ConfigParser import ConfigParser

        config = {
            'verbose' : False,
            'hostname': None,
            'daemon'  : None
            }

        ini = ConfigParser()
        ini.read(CONFIG)

        for (option, value) in ini.items('main'):
            config[option] = value

        fields = res.groupdict()
        if 'hostname' in fields.keys():
            config['hostname'] = fields['hostname']
        if 'daemon' in fields.keys():
            config['daemon'] = fields['daemon']

        import howler
        howler.check(config, fields['userid'], fields['ipaddr'])

        sys.exit(0)

